name             'test_solr'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures test_packagist'
long_description 'Installs/Configures test_packagist'
version          '0.1.0'

depends 'apt'
depends 'solr_app'
